//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoseidonShared.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceView
    {
        public int invoiceId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public int invoiceItemId { get; set; }
        public int StockItemId { get; set; }
        public int Qty { get; set; }
        public decimal SellingPrice { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string GenericName { get; set; }
        public string Origin { get; set; }
    }
}
