//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoseidonShared.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public int Id { get; set; }
        public string Alt { get; set; }
        public string Description { get; set; }
        public Nullable<int> Pack { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> BuyingPrice { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Location { get; set; }
        public string IssueTo { get; set; }
        public string BatchNo { get; set; }
        public string UOM { get; set; }
        public string Origin { get; set; }
        public Nullable<int> SupplierId { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
