//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoseidonShared.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBankAccount
    {
        public int Id { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string AccountTitle { get; set; }
        public string BankName { get; set; }
        public Nullable<decimal> Balance { get; set; }
    }
}
